import type { Teacher } from "./Teachers.types";

export const teachers: Teacher[] = [
  {
    id: "1",
    employeeCode: "EMP00124",
    firstName: "Sarah",
    middleName: "Marie",
    lastName: "Jenkins",
    displayName: "Sarah Jenkins",
    designation: "Teacher",
    department: "Mathematics",
    email: "sarah.jenkins@school.com",
    phone: "+91 9876543210",
    employmentStatus: "ACTIVE",
    joiningDate: "2020-01-15",
    faceRegistered: true,
    remarks: null,
    status: "ACTIVE",
  },
  {
    id: "2",
    employeeCode: "EMP00125",
    firstName: "Michael",
    middleName: "John",
    lastName: "Brown",
    displayName: "Michael Brown",
    designation: "Teacher",
    department: "Science",
    email: "michael.brown@school.com",
    phone: "+91 9876543211",
    employmentStatus: "ACTIVE",
    joiningDate: "2019-06-01",
    faceRegistered: true,
    remarks: null,
    status: "ACTIVE",
  },
  {
    id: "3",
    employeeCode: "EMP00126",
    firstName: "Emily",
    middleName: "Rose",
    lastName: "Clark",
    displayName: "Emily Clark",
    designation: "Teacher",
    department: "English",
    email: "emily.clark@school.com",
    phone: "+91 9876543212",
    employmentStatus: "ON_LEAVE",
    joiningDate: "2021-08-10",
    faceRegistered: false,
    remarks: "On maternity leave",
    status: "INACTIVE",
  },
];