"""Initial schema

Revision ID: 3697c015c43c
Revises: 
Create Date: 2026-07-29 00:17:29.374562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3697c015c43c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', name='user_role'), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'LOCKED', 'DISABLED', name='account_status'), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('password_reset_required', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_public_uuid'), ['public_uuid'], unique=True)

    op.create_table('schools',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), server_default=sa.text("'India'"), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=100), server_default=sa.text("'Asia/Kolkata'"), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_school_code')
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_public_uuid'), ['public_uuid'], unique=True)

    op.create_table('school_configurations',
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('require_check_in_face', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('require_check_out_face', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('require_liveness', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('allow_face_reregistration', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('face_match_threshold', sa.Numeric(precision=3, scale=2), server_default=sa.text('0.65'), nullable=False),
    sa.Column('allow_check_in', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('allow_check_out', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('auto_checkout_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('auto_checkout_time', sa.Time(), nullable=True),
    sa.Column('require_check_in_gps', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('require_check_out_gps', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allowed_radius', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('gps_accuracy_threshold', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('max_failed_login_attempts', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('lockout_duration_minutes', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('allowed_radius > 0', name='allowed_radius_positive'),
    sa.CheckConstraint('face_match_threshold >= 0 AND face_match_threshold <= 1', name='face_match_threshold_range'),
    sa.CheckConstraint('gps_accuracy_threshold > 0', name='gps_accuracy_threshold_positive'),
    sa.CheckConstraint('lockout_duration_minutes >= 1', name='lockout_duration_minutes_positive'),
    sa.CheckConstraint('max_failed_login_attempts >= 1', name='max_failed_login_attempts_positive'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    with op.batch_alter_table('school_configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_configurations_public_uuid'), ['public_uuid'], unique=True)

    op.create_table('teachers',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('official_email', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('department', sa.Enum('ADMINISTRATION', 'MATHEMATICS', 'SCIENCE', 'ENGLISH', 'SOCIAL_SCIENCE', 'COMPUTER', 'SPORTS', 'ART', 'MUSIC', 'LIBRARY', name='department_enum'), nullable=False),
    sa.Column('designation', sa.Enum('PRINCIPAL', 'VICE_PRINCIPAL', 'HOD', 'TEACHER', 'ASSISTANT_TEACHER', 'SPORTS_COACH', 'LIBRARIAN', 'ADMINISTRATOR', name='designation_enum'), nullable=False),
    sa.Column('employment_status', sa.Enum('ACTIVE', 'ON_LEAVE', 'SUSPENDED', 'RESIGNED', 'RETIRED', name='employment_status_enum'), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('face_registered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('employee_code'),
    sa.UniqueConstraint('official_email')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_public_uuid'), ['public_uuid'], unique=True)

    op.create_table('attendances',
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_selfie_path', sa.String(length=500), nullable=False),
    sa.Column('face_match_score', sa.Float(), nullable=True),
    sa.Column('check_in_latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('check_in_longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('check_in_accuracy', sa.Float(), nullable=True),
    sa.Column('check_out_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('check_out_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('check_out_accuracy', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'COMPLETED', 'CORRECTED', name='attendancestatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('corrected_by', sa.BigInteger(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'attendance_date', name='uq_teacher_attendance_date')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendances_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_public_uuid'), ['public_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_attendances_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('teacher_faces',
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('face_quality_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_faces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_faces_public_uuid'), ['public_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_teacher_faces_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_faces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_faces_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_faces_public_uuid'))

    op.drop_table('teacher_faces')
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendances_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_public_uuid'))
        batch_op.drop_index(batch_op.f('ix_attendances_attendance_date'))

    op.drop_table('attendances')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_public_uuid'))

    op.drop_table('teachers')
    with op.batch_alter_table('school_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_configurations_public_uuid'))

    op.drop_table('school_configurations')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_public_uuid'))
        batch_op.drop_index(batch_op.f('ix_schools_code'))

    op.drop_table('schools')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_public_uuid'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
