"""Add GPS location fields to school configuration

Revision ID: 4073161fc448
Revises: 3697c015c43c
Create Date: 2026-07-29 16:41:04.317947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4073161fc448'
down_revision = '3697c015c43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_latitude', sa.Numeric(precision=10, scale=8), nullable=True))
        batch_op.add_column(sa.Column('school_longitude', sa.Numeric(precision=11, scale=8), nullable=True))
        batch_op.add_column(sa.Column('location_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_configurations', schema=None) as batch_op:
        batch_op.drop_column('location_name')
        batch_op.drop_column('school_longitude')
        batch_op.drop_column('school_latitude')

    # ### end Alembic commands ###
