"""add unique school email

Revision ID: 5c3ae9ca4569
Revises: ac9cf3576973
Create Date: 2026-08-13 23:41:47.559196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3ae9ca4569'
down_revision = 'ac9cf3576973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_school_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_constraint('uq_school_email', type_='unique')

    # ### end Alembic commands ###
