"""enforce one active face per teacher

Revision ID: 5fa1affdf7ea
Revises: 5c3ae9ca4569
Create Date: 2026-08-14 12:47:06.557326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa1affdf7ea'
down_revision = '5c3ae9ca4569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_faces', schema=None) as batch_op:
        batch_op.create_index('uq_teacher_faces_active', ['teacher_id'], unique=True, postgresql_where=sa.text('is_active = true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_faces', schema=None) as batch_op:
        batch_op.drop_index('uq_teacher_faces_active', postgresql_where=sa.text('is_active = true'))

    # ### end Alembic commands ###
