"""
update attendance face scores and foreign key behavior

Revision ID: 743c0870ada3
Revises: 5fa1affdf7ea
Create Date: 2026-08-14 21:55:03.751637
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743c0870ada3'
down_revision = '5fa1affdf7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_face_match_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('check_out_selfie_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('check_out_face_match_score', sa.Float(), nullable=True))
        batch_op.drop_constraint(batch_op.f('attendances_teacher_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('attendances_corrected_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'accounts', ['corrected_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('face_match_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendances_corrected_by_fkey'), 'accounts', ['corrected_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('attendances_teacher_id_fkey'), 'teachers', ['teacher_id'], ['id'])
        batch_op.drop_column('check_out_face_match_score')
        batch_op.drop_column('check_out_selfie_path')
        batch_op.drop_column('check_in_face_match_score')

    # ### end Alembic commands ###
