"""Add school to accounts

Revision ID: 79516a26916e
Revises: 8c804b3271e9
Create Date: 2026-08-13 22:31:21.134673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79516a26916e'
down_revision = '8c804b3271e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.BigInteger(), nullable=False))
        batch_op.create_index(batch_op.f('ix_accounts_school_id'), ['school_id'], unique=False)
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('school_configurations', schema=None) as batch_op:
        batch_op.create_check_constraint('liveness_threshold_range', 'liveness_threshold >= 0 AND liveness_threshold <= 1')
        batch_op.create_check_constraint('school_latitude_range', 'school_latitude IS NULL OR (school_latitude >= -90 AND school_latitude <= 90)')
        batch_op.create_check_constraint('school_longitude_range', 'school_longitude IS NULL OR (school_longitude >= -180 AND school_longitude <= 180)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_configurations', schema=None) as batch_op:
        batch_op.drop_constraint('school_longitude_range', type_='check')
        batch_op.drop_constraint('school_latitude_range', type_='check')
        batch_op.drop_constraint('liveness_threshold_range', type_='check')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_accounts_school_id'))
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###
