"""create school and school configuration tables

Revision ID: 8a5eebb99cd1
Revises: 8d9ddd6d49c4
Create Date: 2026-07-28 15:53:56.220137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5eebb99cd1'
down_revision = '8d9ddd6d49c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), server_default=sa.text("'India'"), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=100), server_default=sa.text("'Asia/Kolkata'"), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_school_code'),
    sa.UniqueConstraint('public_uuid')
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_code'), ['code'], unique=False)

    op.create_table('school_configurations',
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('require_check_in_face', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('require_check_out_face', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('require_liveness', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('allow_face_reregistration', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('face_match_threshold', sa.Numeric(precision=3, scale=2), server_default=sa.text('0.65'), nullable=False),
    sa.Column('allow_check_in', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('allow_check_out', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('auto_checkout_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('auto_checkout_time', sa.Time(), nullable=True),
    sa.Column('require_check_in_gps', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('require_check_out_gps', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allowed_radius', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('gps_accuracy_threshold', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('max_failed_login_attempts', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('lockout_duration_minutes', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('allowed_radius > 0', name='allowed_radius_positive'),
    sa.CheckConstraint('face_match_threshold >= 0 AND face_match_threshold <= 1', name='face_match_threshold_range'),
    sa.CheckConstraint('gps_accuracy_threshold > 0', name='gps_accuracy_threshold_positive'),
    sa.CheckConstraint('lockout_duration_minutes >= 1', name='lockout_duration_minutes_positive'),
    sa.CheckConstraint('max_failed_login_attempts >= 1', name='max_failed_login_attempts_positive'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_uuid'),
    sa.UniqueConstraint('school_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_configurations')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_code'))

    op.drop_table('schools')
    # ### end Alembic commands ###
