"""Add liveThreshold fields to school configuration

Revision ID: 8c804b3271e9
Revises: 4073161fc448
Create Date: 2026-07-30 23:54:47.745383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c804b3271e9'
down_revision = '4073161fc448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liveness_threshold', sa.Numeric(precision=3, scale=2), server_default=sa.text('0.80'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_configurations', schema=None) as batch_op:
        batch_op.drop_column('liveness_threshold')

    # ### end Alembic commands ###
