"""create attendances table

Revision ID: 8ccfd59e4831
Revises: cfd10a8918c5
Create Date: 2026-07-21 00:41:40.420573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ccfd59e4831'
down_revision = 'cfd10a8918c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_selfie_path', sa.String(length=500), nullable=False),
    sa.Column('face_match_score', sa.Float(), nullable=True),
    sa.Column('check_in_latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('check_in_longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('check_in_accuracy', sa.Float(), nullable=True),
    sa.Column('check_out_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('check_out_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('check_out_accuracy', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'COMPLETED', 'CORRECTED', name='attendancestatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('corrected_by', sa.BigInteger(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_uuid'),
    sa.UniqueConstraint('teacher_id', 'attendance_date', name='uq_teacher_attendance_date')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendances_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendances_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_attendance_date'))

    op.drop_table('attendances')
    # ### end Alembic commands ###
