"""create teacher_faces table

Revision ID: 8d9ddd6d49c4
Revises: 8ccfd59e4831
Create Date: 2026-07-25 19:18:22.613796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d9ddd6d49c4'
down_revision = '8ccfd59e4831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_faces',
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('face_quality_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_uuid')
    )
    with op.batch_alter_table('teacher_faces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_faces_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_faces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_faces_teacher_id'))

    op.drop_table('teacher_faces')
    # ### end Alembic commands ###
