"""Initial database schema

Revision ID: cfd10a8918c5
Revises: 
Create Date: 2026-07-18 15:13:37.498104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd10a8918c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', name='user_role'), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'LOCKED', 'DISABLED', name='account_status'), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('password_reset_required', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_uuid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('teachers',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('official_email', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('department', sa.Enum('ADMINISTRATION', 'MATHEMATICS', 'SCIENCE', 'ENGLISH', 'SOCIAL_SCIENCE', 'COMPUTER', 'SPORTS', 'ART', 'MUSIC', 'LIBRARY', name='department_enum'), nullable=False),
    sa.Column('designation', sa.Enum('PRINCIPAL', 'VICE_PRINCIPAL', 'HOD', 'TEACHER', 'ASSISTANT_TEACHER', 'SPORTS_COACH', 'LIBRARIAN', 'ADMINISTRATOR', name='designation_enum'), nullable=False),
    sa.Column('employment_status', sa.Enum('ACTIVE', 'ON_LEAVE', 'SUSPENDED', 'RESIGNED', 'RETIRED', name='employment_status_enum'), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('face_registered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('employee_code'),
    sa.UniqueConstraint('official_email'),
    sa.UniqueConstraint('public_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    op.drop_table('accounts')
    # ### end Alembic commands ###
